"""initial schema

Revision ID: 692b15c1a813
Revises: 
Create Date: 2026-08-28 08:49:37.420731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692b15c1a813'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.user.UUID(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='E.164 format, e.g. +256701234567'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pin_hash', sa.String(length=128), nullable=False, comment='BCrypt hash of 4-digit USSD PIN'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_level', sa.String(length=20), nullable=False, comment='none | tier1 | tier2'),
    sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('daily_limit_usd', sa.Float(), nullable=False),
    sa.Column('monthly_limit_usd', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_ussd_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('transactions',
    sa.Column('id', app.models.transaction.UUID(length=36), nullable=False),
    sa.Column('user_id', app.models.transaction.UUID(length=36), nullable=False),
    sa.Column('type', sa.Enum('FUND', 'SEND', 'RECEIVE', 'SPEND', 'SWAP', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'PROCESSING', 'SETTLED', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False, comment='Our internal reference (e.g. SC-A1B2C3D4E5F6)'),
    sa.Column('amount_fiat', sa.Float(), nullable=False, comment='Amount in local currency'),
    sa.Column('currency_fiat', sa.String(length=3), nullable=False, comment='ISO 4217, e.g. UGX'),
    sa.Column('amount_sats', sa.BigInteger(), nullable=False, comment='Amount in satoshis'),
    sa.Column('fee_sats', sa.BigInteger(), nullable=False, comment='Lightning network fee'),
    sa.Column('rate_used', sa.Float(), nullable=False, comment='sats per unit of fiat'),
    sa.Column('rate_source', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False, comment='mtn_momo | airtel_money | orange_money | lightning'),
    sa.Column('provider_txn_id', sa.String(length=100), nullable=True, comment="Provider's own transaction ID"),
    sa.Column('provider_status', sa.String(length=30), nullable=True, comment='Raw status from provider'),
    sa.Column('payment_hash', sa.String(length=64), nullable=True, comment='Lightning payment hash (for send/receive)'),
    sa.Column('payment_request', sa.Text(), nullable=True, comment='BOLT11 invoice string'),
    sa.Column('destination_pubkey', sa.String(length=66), nullable=True, comment='Lightning node pubkey (for send)'),
    sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Phone number used for mobile money'),
    sa.Column('merchant_name', sa.String(length=100), nullable=True, comment='Merchant name (for card spend)'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Additional data as JSON string'),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pending_at', sa.DateTime(), nullable=True),
    sa.Column('processing_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_tx_provider_txn', ['provider_txn_id'], unique=False)
        batch_op.create_index('idx_tx_reference', ['reference'], unique=True)
        batch_op.create_index('idx_tx_status', ['status'], unique=False)
        batch_op.create_index('idx_tx_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('ussd_sessions',
    sa.Column('id', app.models.ussd_session.UUID(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='Session ID from the USSD gateway'),
    sa.Column('user_id', app.models.ussd_session.UUID(length=36), nullable=True, comment="Null if user hasn't registered yet"),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('current_screen', sa.String(length=50), nullable=False, comment='Current USSD screen/menu'),
    sa.Column('accumulated_input', sa.Text(), nullable=True, comment='JSON string of accumulated user input across screens'),
    sa.Column('menu_depth', sa.Integer(), nullable=False, comment='How deep in the menu tree (0 = main menu)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ussd_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ussd_sessions_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_ussd_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('wallets',
    sa.Column('id', app.models.wallet.UUID(length=36), nullable=False),
    sa.Column('user_id', app.models.wallet.UUID(length=36), nullable=False),
    sa.Column('balance_sats', sa.BigInteger(), nullable=False, comment='Available BTC balance in satoshis'),
    sa.Column('reserved_sats', sa.BigInteger(), nullable=False, comment='Sats locked in pending transactions'),
    sa.Column('balance_usd', sa.Float(), nullable=False, comment='Available USD balance'),
    sa.Column('reserved_usd', sa.Float(), nullable=False, comment='USD locked in pending transactions'),
    sa.Column('lnd_pubkey', sa.String(length=66), nullable=True, comment='LND node public key'),
    sa.Column('lnd_address', sa.String(length=255), nullable=True, comment='Lightning node address (pubkey@host)'),
    sa.Column('card_number', sa.String(length=19), nullable=True, comment='Virtual card number (encrypted at rest)'),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry', sa.String(length=5), nullable=True, comment='MM/YY'),
    sa.Column('card_status', sa.String(length=20), nullable=False, comment='inactive | active | frozen | closed'),
    sa.Column('daily_spent_sats', sa.BigInteger(), nullable=False),
    sa.Column('daily_spent_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_spent_sats', sa.BigInteger(), nullable=False),
    sa.Column('monthly_spent_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('balance_sats >= 0', name='positive_balance'),
    sa.CheckConstraint('reserved_sats >= 0', name='positive_reserved'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    with op.batch_alter_table('ussd_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ussd_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_ussd_sessions_phone_number'))

    op.drop_table('ussd_sessions')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_tx_user_created')
        batch_op.drop_index('idx_tx_status')
        batch_op.drop_index('idx_tx_reference')
        batch_op.drop_index('idx_tx_provider_txn')

    op.drop_table('transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    # ### end Alembic commands ###
